services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./src:/var/www/html/

  php:
    build: ./php/
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html/
    links:
      - mysql
  app-data:    
    build: ./php/
    container_name: app-data-container  
    volumes:  
      - ./src:/var/www/html/  
    command: "true"  

  mysql:    
    build: ./mysql/
    container_name: mysql-container  
    volumes_from:  
      - mysql-data  
    environment:  
      MYSQL_ROOT_PASSWORD: secret  
      MYSQL_DATABASE: mydb  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: password 
    expose:
      - 3306
    ports:
      - 3306:3306
    # volumes:
    #   - ~/code/docker-development/logs/mysql:/var/log/mysql
      # - ~/code/docker-development/mysql/config:/etc/mysql

  mysql-data:    
    build: ./mysql/
    container_name: mysql-data-container  
    volumes:  
     - /var/lib/mysql  
    command: "true" 