<?php
define("DIRBASEURL","/und7/Contactos/public/index.php");
define("DIRPUBLIC","/und7/Contactos/public");
define("DBHOST","mysql");
define("DBUSER","myuser");
define("DBPASS","password");
define("DBNAME","mydb");
define("DBPORT","3306");
?>